#!/bin/bash
if [[ $1 = "on" ]];
then
    export http_proxy=http://127.0.0.1:1087;
    export https_proxy=http://127.0.0.1:1087;
    echo 'proxy start on port 1087'
fi

if [[ $1 = "off" ]];
then
    unset http_proxy
    unset https_proxy
    echo 'proxy cleared'
fi
